name: Workflow
on: push
jobs:
  image:
    strategy:
      matrix:
        include:
          - { arch: amd64, ghc: 9.2.5, hls: 85f788135175a007d3db4ac911c4115b30ab9d87 }
          - { arch: arm64, ghc: 9.2.5, hls: 85f788135175a007d3db4ac911c4115b30ab9d87 }
    runs-on: ubuntu-latest
    steps:

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-haskell-${{ matrix.arch }}
          buildspec-override: aws/image.yaml
          env-vars-for-codebuild: GHC_VERSION,HLS_VERSION
        env:
          GHC_VERSION: ${{ matrix.ghc }}
          HLS_VERSION: ${{ matrix.hls }}

  manifest:
    needs: image
    strategy:
      matrix:
        ghc:
          - 9.2.5
    runs-on: ubuntu-latest
    steps:

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: docker-haskell-amd64
          buildspec-override: aws/manifest.yaml
          env-vars-for-codebuild: GHC_VERSION
        env:
          GHC_VERSION: ${{ matrix.ghc }}
