{
  "jobs": {
    "image": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "aws-actions/configure-aws-credentials@v4",
          "with": {
            "aws-access-key-id": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "aws-region": "${{ secrets.AWS_DEFAULT_REGION }}",
            "aws-secret-access-key": "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          }
        },
        {
          "env": {
            "GHC_VERSION": "${{ matrix.ghc }}"
          },
          "uses": "aws-actions/aws-codebuild-run-build@v1",
          "with": {
            "buildspec-override": "aws/image.yaml",
            "env-vars-for-codebuild": "GHC_VERSION",
            "project-name": "docker-haskell-${{ matrix.arch }}"
          }
        }
      ],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "include": [
            {
              "arch": "amd64",
              "ghc": "9.4.8"
            },
            {
              "arch": "amd64",
              "ghc": "9.6.5"
            },
            {
              "arch": "amd64",
              "ghc": "9.8.2"
            },
            {
              "arch": "arm64",
              "ghc": "9.4.8"
            },
            {
              "arch": "arm64",
              "ghc": "9.6.5"
            },
            {
              "arch": "arm64",
              "ghc": "9.8.2"
            }
          ]
        }
      }
    },
    "manifest": {
      "needs": "image",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "aws-actions/configure-aws-credentials@v4",
          "with": {
            "aws-access-key-id": "${{ secrets.AWS_ACCESS_KEY_ID }}",
            "aws-region": "${{ secrets.AWS_DEFAULT_REGION }}",
            "aws-secret-access-key": "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          }
        },
        {
          "env": {
            "GHC_VERSION": "${{ matrix.ghc }}",
            "LATEST": "${{ github.ref == 'refs/heads/main' }}"
          },
          "uses": "aws-actions/aws-codebuild-run-build@v1",
          "with": {
            "buildspec-override": "aws/manifest.yaml",
            "env-vars-for-codebuild": "GHC_VERSION,LATEST",
            "project-name": "docker-haskell-amd64"
          }
        }
      ],
      "strategy": {
        "matrix": {
          "ghc": [
            "9.4.8",
            "9.6.5",
            "9.8.2"
          ]
        }
      }
    }
  },
  "name": "Workflow",
  "on": "push"
}
