name: Workflow
on: push
jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { ghc: 9.0.2, hls: 830596ee212d4f2fbbc81bcf5d08574ae96947d3 }
          - { ghc: 9.2.4, hls: 830596ee212d4f2fbbc81bcf5d08574ae96947d3 }
          - { ghc: 9.4.2, hls: 830596ee212d4f2fbbc81bcf5d08574ae96947d3 }
    name: Docker with GHC ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: latest=false
          tags: |
            type=sha,format=long,prefix=${{ matrix.ghc }}-
            type=raw,value=${{ matrix.ghc }},enable={{ is_default_branch }}
      - uses: docker/login-action@v2
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v3
        with:
          build-args: |
            GHC_VERSION=${{ matrix.ghc }}
            HLS_VERSION=${{ matrix.hls }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
